apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  S3_ENDPOINT: "s3.cn-north-1.qiniucs.com"
  S3_BUCKET: "wan22"
  S3_ACCESS_KEY: "S2f5jvYEkIwJVcRsVBRvYj7K19bIiJD7LDch466I"
  S3_SECRET_KEY: "ReP83uC9xKWM5S9btrpJoWUZF-wMVnip3DEGf3ou"