apiVersion: "kubeflow.org/v1"
kind: PyTorchJob
metadata:
  name: wan22-i2v-distributed2-s3
spec:
  runPolicy:
    cleanPodPolicy: None # 可选值: All, Running, None. All 表示任务结束后清理所有 Pod
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          initContainers:
            - name: download-image
              image: 172.31.0.182/system_containers/aws-cli:2.13.0
              command:
                - "aws"
                - "s3"
                - "--endpoint-url"
                - "https://s3.cn-north-1.qiniucs.com"
                - "cp"
                - "s3://wan22/i2v_input.JPG"
                - "/image-data/input.jpg"
              env:
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_ACCESS_KEY
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_SECRET_KEY
              volumeMounts:
                - name: image-volume
                  mountPath: /image-data
          containers:
            - name: pytorch
              image: 172.31.0.182/system_containers/wan22:1024
              imagePullPolicy: Always
              command:
                - "torchrun"
              args:
                - "--nproc_per_node=2"
                - "generate.py"
                - "--task"
                - "i2v-A14B"
                - "--size"
                - "832*480"
                - "--ckpt_dir"
                - "/data/Wan2.2-I2V-A14B"
                - "--image"
                - "/image-data/input.jpg"
                - "--dit_fsdp"
                - "--t5_fsdp"
                - "--convert_model_dtype"
                - "--ulysses_size"
                - "4"
                - "--sample_guide_scale"
                - "10"
                - "--prompt"
                - "刘亦菲和特朗普身着舒适的拳击装备，戴着鲜艳的拳套，在聚光灯照耀的舞台上激烈地搏斗"
                - "--save_file"
                - "/output/wan22-i2v-distributed2.mp4"
                - "--s3_endpoint_url"
                - "https://s3.cn-north-1.qiniucs.com"
                - "--s3_bucket"
                - "wan22"
                - "--s3_key_prefix"
                - "wan22-i2v-task-20251024112355"
              resources:
                requests:
                  cpu: "4"
                limits:
                  cpu: "64"
                  memory: 256Gi
                  nvidia.com/gpu: "2"
                  t7d.com/rdma: "1"
              env:
                - name: WAN_FRAME_NUM
                  value: "241"
                - name: NVIDIA_VISIBLE_DEVICES
                  value: "all"
                - name: NCCL_IB_DISABLE
                  value: "0"
                - name: NCCL_SOCKET_IFNAME
                  value: "^lo,docker0,veth"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_ACCESS_KEY
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_SECRET_KEY
              volumeMounts:
                - name: data-volume
                  mountPath: /data/Wan2.2-I2V-A14B
                - name: output-volume
                  mountPath: /output
                - name: dshm
                  mountPath: /dev/shm
                - name: image-volume
                  mountPath: /image-data
          volumes:
            - name: data-volume
              hostPath:
                path: /data/Wan-AI/Wan2.2-I2V-A14B
            - name: output-volume
              hostPath:
                path: /data/Wan-AI/output
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 128Gi
            - name: image-volume
              emptyDir: {}
    Worker:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          initContainers:
            - name: download-image
              image: 172.31.0.182/system_containers/aws-cli:2.13.0
              command:
                - "aws"
                - "s3"
                - "--endpoint-url"
                - "https://s3.cn-north-1.qiniucs.com"
                - "cp"
                - "s3://wan22/i2v_input.JPG"
                - "/image-data/input.jpg"
              env:
                - name: WAN_FRAME_NUM
                  value: "241"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_ACCESS_KEY
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_SECRET_KEY
              volumeMounts:
                - name: image-volume
                  mountPath: /image-data
          containers:
            - name: pytorch
              image: 172.31.0.182/system_containers/wan22:1024
              imagePullPolicy: Always
              command:
                - "torchrun"
              args:
                - "--nproc_per_node=2"
                - "generate.py"
                - "--task"
                - "i2v-A14B"
                - "--size"
                - "832*480"
                - "--ckpt_dir"
                - "/data/Wan2.2-I2V-A14B"
                - "--image"
                - "/image-data/input.jpg"
                - "--dit_fsdp"
                - "--t5_fsdp"
                - "--convert_model_dtype"
                - "--ulysses_size"
                - "4"
                - "--sample_guide_scale"
                - "10"
                - "--prompt"
                - "刘亦菲和特朗普身着舒适的拳击装备，戴着鲜艳的拳套，在聚光灯照耀的舞台上激烈地搏斗"
                - "--save_file"
                - "/output/wan22-i2v-distributed2.mp4"
                - "--s3_endpoint_url"
                - "https://s3.cn-north-1.qiniucs.com"
                - "--s3_bucket"
                - "wan22"
                - "--s3_key_prefix"
                - "wan22-i2v-task-20251024112355"
              resources:
                requests:
                  cpu: "4"
                limits:
                  cpu: "64"
                  memory: 256Gi
                  nvidia.com/gpu: "2"
                  t7d.com/rdma: "1"
              env:
                - name: NVIDIA_VISIBLE_DEVICES
                  value: "all"
                - name: NCCL_IB_DISABLE
                  value: "0"
                - name: NCCL_SOCKET_IFNAME
                  value: "^lo,docker0,veth"
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_ACCESS_KEY
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: s3-credentials
                      key: S3_SECRET_KEY
              volumeMounts:
                - name: data-volume
                  mountPath: /data/Wan2.2-I2V-A14B
                - name: output-volume
                  mountPath: /output
                - name: dshm
                  mountPath: /dev/shm
                - name: image-volume
                  mountPath: /image-data
          volumes:
            - name: data-volume
              hostPath:
                path: /data/Wan-AI/Wan2.2-I2V-A14B
            - name: output-volume
              hostPath:
                path: /data/Wan-AI/output
            - name: dshm
              emptyDir:
                medium: Memory
                sizeLimit: 128Gi
            - name: image-volume
              emptyDir: {}